# ------------------- General Options -------------------------
description                  : AB3DMOT
seed                         : 0

# --------------- main.py
save_root                    : ./AB3Dmot/results/OPV2V
dataset                      : OPV2V      # KITTI
split                        : train        # train, test
det_name                     : pointpillar-CoBEVT-nocompression  # name of the detector [pointrcnn, pvrcnn, pointpillar_CoBEVT_nocompression]
cat_list                     : ['Car']

score_threshold              : -10000     # filter out tracklet with low confidence if necessary, default no filtering here but do it in trk_conf_threshold.py
num_hypo                     : 1          # >1 to allow multi-hypothesis tracking

# --------------- model.py
ego_com                      : true      # turn on only slightly reduce speed but increase a lot for performance
vis                          : false       # only for debug or visualization purpose, will significantly reduce speed
affi_pro                     : true